[server]
headless = true
port = 10000
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "light"
